name: Create New Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release and Upload WSDL
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} mplusqapi.wsdl --title "${{ github.ref_name }}" --notes ""
