<?php declare(strict_types=1);
// Generated code
namespace MplusKASSA\MplusQapi;
class ArticleSpecialPrice {
	const PRICE_NORMAL = 'PRICE-NORMAL';
	const PRICE_FREE = 'PRICE-FREE';
	const PRICE_ASK_POSITIVE = 'PRICE-ASK-POSITIVE';
	const PRICE_ASK_NEGATIVE = 'PRICE-ASK-NEGATIVE';
	const PRICE_ASK_POSITIVE_NO_POPUP = 'PRICE-ASK-POSITIVE-NO-POPUP';
	const PRICE_ASK_NEGATIVE_NO_POPUP = 'PRICE-ASK-NEGATIVE-NO-POPUP';
	const PRICE_NOT_FOR_SALE = 'PRICE-NOT-FOR-SALE';
	const PRICE_BARCODE_PRICE = 'PRICE-BARCODE-PRICE';
	const PRICE_NOT_SET = 'PRICE-NOT-SET';
}
class CardType {
	const EMPLOYEE = 'EMPLOYEE';
	const PRODUCT = 'PRODUCT';
	const RELATION = 'RELATION';
}
class PaymentMethodType {
	const PAYMENT = 'PAYMENT-METHOD-TYPE-PAYMENT';
	const EFT = 'PAYMENT-METHOD-TYPE-EFT';
	const SUSPENSE = 'PAYMENT-METHOD-TYPE-SUSPENSE';
	const DEPOSIT = 'PAYMENT-METHOD-TYPE-DEPOSIT';
	const AUTO_DEPOSIT = 'PAYMENT-METHOD-TYPE-AUTO-DEPOSIT';
	const BPE = 'PAYMENT-METHOD-TYPE-BPE';
	const VOUCHER_BPE = 'PAYMENT-METHOD-TYPE-VOUCHER-BPE';
	const VOUCHER_BOOK_BPE = 'PAYMENT-METHOD-TYPE-VOUCHER-BOOK-BPE';
}
class BpeBudgetPeriod {
	const DAY = 'DAY';
	const WEEK = 'WEEK';
	const MONTH = 'MONTH';
}
class BpeBudgetExceededAction {
	const IGNORING = 'IGNORING';
	const WARNING = 'WARNING';
	const BLOCKING = 'BLOCKING';
}
class BpeBudgetNoValueDefaultLimit {
	const ZERO = 'ZERO';
	const UNLIMITED = 'UNLIMITED';
}
class EftTransactionState {
	const UNKNOWN = 'EFT-TRANSACTION-STATE-UNKNOWN';
	const PAID = 'EFT-TRANSACTION-STATE-PAID';
	const RECOVERED = 'EFT-TRANSACTION-STATE-RECOVERED';
	const NOT_PAID = 'EFT-TRANSACTION-STATE-NOT-PAID';
	const PAID_MANUALLY = 'EFT-TRANSACTION-STATE-PAID-MANUALLY';
	const REPRINT = 'EFT-TRANSACTION-STATE-REPRINT';
	const POS_AUTHORIZATION_STARTED = 'EFT-TRANSACTION-STATE-POS-AUTHORIZATION-STARTED';
	const POS_AUTHORIZATION_PAID = 'EFT-TRANSACTION-STATE-POS-AUTHORIZATION-PAID';
	const POS_AUTHORIZATION_NOT_PAID = 'EFT-TRANSACTION-STATE-POS-AUTHORIZATION-NOT-PAID';
	const PAID_OFFLINE = 'EFT-TRANSACTION-STATE-PAID-OFFLINE';
}
class TerminalStatus {
	const AVAILABLE = 'TERMINAL-STATUS-AVAILABLE';
	const REGISTERED = 'TERMINAL-STATUS-REGISTERED';
}
class TurnoverGroupType {
	const TURNOVER = 'TURNOVER-GROUP-TYPE-TURNOVER';
	const PAYMENT = 'TURNOVER-GROUP-TYPE-PAYMENT';
	const SUSPENSE = 'TURNOVER-GROUP-TYPE-SUSPENSE';
	const CASH_INFLOW = 'TURNOVER-GROUP-TYPE-CASH-INFLOW';
	const CASH_OUTFLOW = 'TURNOVER-GROUP-TYPE-CASH-OUTFLOW';
	const BALANCE_UPGRADE = 'TURNOVER-GROUP-TYPE-BALANCE-UPGRADE';
	const UNKNOWN = 'TURNOVER-GROUP-TYPE-UNKNOWN';
}
class IdempotencyResult {
	const ORIGINAL_RESPONSE = 'IDEMPOTENCY-RESULT-ORIGINAL-RESPONSE';
	const REPLAY_RESPONSE = 'IDEMPOTENCY-RESULT-REPLAY-RESPONSE';
}
class VatMethod {
	const INCLUSIVE = 'VAT-METHOD-INCLUSIVE';
	const EXCLUSIVE = 'VAT-METHOD-EXCLUSIVE';
	const SHIFTED = 'VAT-METHOD-SHIFTED';
	const NONE = 'VAT-METHOD-NONE';
}
class VatChange {
	const TAKE_OUT = 'VAT-CHANGE-TAKE-OUT';
	const EAT_HERE = 'VAT-CHANGE-EAT-HERE';
	const CUSTOM_TAKE_OUT = 'VAT-CHANGE-CUSTOM-TAKE-OUT';
	const CUSTOM_EAT_HERE = 'VAT-CHANGE-CUSTOM-EAT-HERE';
}
class OrderType {
	const SALES_ORDER = 'ORDER-TYPE-SALES-ORDER';
	const REPEAT_SALES_ORDER = 'ORDER-TYPE-REPEAT-SALES-ORDER';
	const EXTERNAL_SALES_ORDER = 'ORDER-TYPE-EXTERNAL-SALES-ORDER';
	const TABLE_ORDER = 'ORDER-TYPE-TABLE-ORDER';
	const CAFETERIA_ORDER = 'ORDER-TYPE-CAFETERIA-ORDER';
}
class OrderDeliveryState {
	const NOTHING = 'ORDER-DELIVERY-STATE-NOTHING';
	const PARTIAL = 'ORDER-DELIVERY-STATE-PARTIAL';
	const COMPLETE = 'ORDER-DELIVERY-STATE-COMPLETE';
}
class OrderCancelState {
	const NOTHING = 'ORDER-CANCEL-STATE-NOTHING';
	const PARTIAL = 'ORDER-CANCEL-STATE-PARTIAL';
	const COMPLETE = 'ORDER-CANCEL-STATE-COMPLETE';
}
class OrderCompleteState {
	const NOTHING = 'ORDER-COMPLETE-STATE-NOTHING';
	const PARTIAL = 'ORDER-COMPLETE-STATE-PARTIAL';
	const PARTIAL_DELIVERY_PENDING = 'ORDER-COMPLETE-STATE-PARTIAL-DELIVERY-PENDING';
	const COMPLETE = 'ORDER-COMPLETE-STATE-COMPLETE';
}
class LineType {
	const NONE = 'LINE-TYPE-NONE';
	const PREPARATION = 'LINE-TYPE-PREPARATION';
	const COMPONENT = 'LINE-TYPE-COMPONENT';
}
class VoucherRedeemPeriod {
	const DAY = 'DAY';
	const WEEK = 'WEEK';
	const MONTH = 'MONTH';
	const YEAR = 'YEAR';
}
class DataType {
	const STRING = 'DATA-TYPE-STRING';
	const INT = 'DATA-TYPE-INT';
	const DECIMAL = 'DATA-TYPE-DECIMAL';
	const BOOL = 'DATA-TYPE-BOOL';
	const DATE = 'DATA-TYPE-DATE';
	const DATETIME = 'DATA-TYPE-DATETIME';
	const ARRAY = 'DATA-TYPE-ARRAY';
	const MULTISELECTINT = 'DATA-TYPE-MULTISELECTINT';
	const UNKNOWN = 'DATA-TYPE-UNKNOWN';
}
class LogMistakeResult {
	const LOG_MISTAKE_OK = 'LOG-MISTAKE-OK';
	const LOG_MISTAKE_NOTHING_TO_LOG = 'LOG-MISTAKE-NOTHING-TO-LOG';
	const LOG_MISTAKE_FAILED = 'LOG-MISTAKE-FAILED';
}
class LoadFileResult {
	const LOAD_FILE_OK = 'LOAD-FILE-OK';
	const LOAD_FILE_NOT_REQUESTED = 'LOAD-FILE-NOT-REQUESTED';
	const LOAD_FILE_NOT_FOUND = 'LOAD-FILE-NOT-FOUND';
	const LOAD_FILE_NOT_PERMITTED = 'LOAD-FILE-NOT-PERMITTED';
	const LOAD_FILE_UNKNOWN_ERROR = 'LOAD-FILE-UNKNOWN-ERROR';
}
class GetRelationResult {
	const OK = 'GET-RELATION-RESULT-OK';
	const NOT_FOUND = 'GET-RELATION-RESULT-NOT-FOUND';
}
class CreateRelationResult {
	const OK = 'CREATE-RELATION-RESULT-OK';
	const FAILED = 'CREATE-RELATION-RESULT-FAILED';
	const FAILED_RELATION_NUMBER_ALREADY_TAKEN = 'CREATE-RELATION-RESULT-FAILED-RELATION-NUMBER-ALREADY-TAKEN';
}
class UpdateRelationResult {
	const OK = 'UPDATE-RELATION-RESULT-OK';
	const NOT_FOUND = 'UPDATE-RELATION-RESULT-NOT-FOUND';
	const FAILED = 'UPDATE-RELATION-RESULT-FAILED';
}
class FindRelationResult {
	const OK = 'FIND-RELATION-RESULT-OK';
	const NOT_FOUND = 'FIND-RELATION-RESULT-NOT-FOUND';
}
class AdjustPointsResult {
	const ADJUST_POINTS_RESULT_OK = 'ADJUST-POINTS-RESULT-OK';
	const ADJUST_POINTS_FAILED_RELATION_NOT_FOUND = 'ADJUST-POINTS-FAILED-RELATION-NOT-FOUND';
	const ADJUST_POINTS_FAILED_NO_DIFFERENCE = 'ADJUST-POINTS-FAILED-NO-DIFFERENCE';
	const ADJUST_POINTS_FAILED = 'ADJUST-POINTS-FAILED';
}
class AdjustPointsMode {
	const RELATIVE = 'ADJUST-POINTS-MODE-RELATIVE';
	const ABSOLUTE = 'ADJUST-POINTS-MODE-ABSOLUTE';
}
class GetEmployeeResult {
	const OK = 'GET-EMPLOYEE-RESULT-OK';
	const NOT_FOUND = 'GET-EMPLOYEE-RESULT-NOT-FOUND';
}
class FindEmployeeResult {
	const OK = 'FIND-EMPLOYEE-RESULT-OK';
	const NOT_FOUND = 'FIND-EMPLOYEE-RESULT-NOT-FOUND';
}
class CreateEmployeeResult {
	const OK = 'CREATE-EMPLOYEE-RESULT-OK';
	const FAILED = 'CREATE-EMPLOYEE-RESULT-FAILED';
	const FAILED_EMPLOYEE_NUMBER_ALREADY_TAKEN = 'CREATE-EMPLOYEE-RESULT-FAILED-EMPLOYEE-NUMBER-ALREADY-TAKEN';
}
class UpdateEmployeeResult {
	const OK = 'UPDATE-EMPLOYEE-RESULT-OK';
	const NOT_FOUND = 'UPDATE-EMPLOYEE-RESULT-NOT-FOUND';
	const FAILED = 'UPDATE-EMPLOYEE-RESULT-FAILED';
}
class ArticleAskFor {
	const ASK_FOR_NOTHING = 'ASK-FOR-NOTHING';
	const ASK_FOR_DESCRIPTION = 'ASK-FOR-DESCRIPTION';
	const ASK_FOR_EXTRA = 'ASK-FOR-EXTRA';
	const ASK_FOR_DESCRIPTION_AND_EXTRA = 'ASK-FOR-DESCRIPTION-AND-EXTRA';
}
class TableStatus {
	const OPEN = 'TABLE-STATUS-OPEN';
	const TAKEN = 'TABLE-STATUS-TAKEN';
	const TAKEN_AND_RECEIPT_PRINTED = 'TABLE-STATUS-TAKEN-AND-RECEIPT-PRINTED';
	const TAKEN_AND_ACTION_REQUIRED = 'TABLE-STATUS-TAKEN-AND-ACTION-REQUIRED';
	const TAKEN_AND_TIME_LIMIT_REACHED = 'TABLE-STATUS-TAKEN-AND-TIME-LIMIT-REACHED';
	const ORDER_READY_TO_BE_SERVED = 'TABLE-STATUS-ORDER-READY-TO-BE-SERVED';
	const RECENTLY_PAID = 'TABLE-STATUS-RECENTLY-PAID';
}
class CourseType {
	const STANDARD = 'COURSE-TYPE-STANDARD';
	const BAR = 'COURSE-TYPE-BAR';
}
class DiscountType {
	const NONE = 'DISCOUNT-TYPE-NONE';
	const PRICE_GROUP = 'DISCOUNT-TYPE-PRICE-GROUP';
	const SALES_PRICE = 'DISCOUNT-TYPE-SALES-PRICE';
	const CUSTOMER_DISCOUNT = 'DISCOUNT-TYPE-CUSTOMER-DISCOUNT';
	const BRANCH_PRICE = 'DISCOUNT-TYPE-BRANCH-PRICE';
	const EXTERNAL_DISCOUNT = 'DISCOUNT-TYPE-EXTERNAL-DISCOUNT';
	const SALE_PROMOTION = 'DISCOUNT-TYPE-SALE-PROMOTION';
	const SALE_PROMOTION_RETOUR = 'DISCOUNT-TYPE-SALE-PROMOTION-RETOUR';
	const SALE_PROMOTION_FREE_ARTICLE = 'DISCOUNT-TYPE-SALE-PROMOTION-FREE-ARTICLE';
}
class PriceType {
	const UNKNOWN = 'PRICE-TYPE-UNKNOWN';
	const ARTICLE = 'PRICE-TYPE-ARTICLE';
	const SPECIAL = 'PRICE-TYPE-SPECIAL';
	const POINT = 'PRICE-TYPE-POINT';
	const PAYMENT = 'PRICE-TYPE-PAYMENT';
	const BRANCH = 'PRICE-TYPE-BRANCH';
	const MENU_MAIN_ARTICLE = 'PRICE-TYPE-MENU-MAIN-ARTICLE';
	const SUB_ADDITION = 'PRICE-TYPE-SUB-ADDITION';
	const EXCHANGE_RATE_BUY = 'PRICE-TYPE-EXCHANGE-RATE-BUY';
	const EXCHANGE_RATE_SELL = 'PRICE-TYPE-EXCHANGE-RATE-SELL';
	const GIFT_CARD = 'PRICE-TYPE-GIFT-CARD';
	const SALES_PROMOTIONS_PACKAGE = 'PRICE-TYPE-SALES-PROMOTIONS-PACKAGE';
	const FIXED = 'PRICE-TYPE-FIXED';
}
class SaveTableOrderResult {
	const OK = 'SAVE-TABLE-ORDER-RESULT-OK';
	const FAILED = 'SAVE-TABLE-ORDER-RESULT-FAILED';
	const ORDER_HAS_CHANGED = 'SAVE-TABLE-ORDER-RESULT-ORDER-HAS-CHANGED';
	const NO_CHANGES = 'SAVE-TABLE-ORDER-RESULT-NO-CHANGES';
}
class CreateAndPayTableOrderResult {
	const OK = 'CREATE-AND-PAY-TABLE-ORDER-RESULT-OK';
	const FAILED = 'CREATE-AND-PAY-TABLE-ORDER-RESULT-FAILED';
	const PAYMENT_INSUFFICIENT = 'CREATE-AND-PAY-TABLE-ORDER-RESULT-PAYMENT-INSUFFICIENT';
	const PAYMENT_FAILED = 'CREATE-AND-PAY-TABLE-ORDER-RESULT-PAYMENT-FAILED';
}
class MoveTableOrderResult {
	const OK = 'MOVE-TABLE-ORDER-RESULT-OK';
	const FAILED = 'MOVE-TABLE-ORDER-RESULT-FAILED';
	const ORDER_HAS_CHANGED = 'MOVE-TABLE-ORDER-RESULT-ORDER-HAS-CHANGED';
}
class GetTableOrderResult {
	const OK = 'GET-TABLE-ORDER-RESULT-OK';
	const NONE = 'GET-TABLE-ORDER-RESULT-NONE';
	const ALREADY_USED = 'GET-TABLE-ORDER-RESULT-ALREADY-USED';
	const CLAIMED = 'GET-TABLE-ORDER-RESULT-CLAIMED';
}
class ReleaseTableOrderResult {
	const OK = 'RELEASE-TABLE-ORDER-RESULT-OK';
	const NOT_CLAIMED = 'RELEASE-TABLE-ORDER-RESULT-NOT-CLAIMED';
	const CLAIMED_BY_OTHER = 'RELEASE-TABLE-ORDER-RESULT-CLAIMED-BY-OTHER';
}
class GetTableOrderCourseListResult {
	const GET_TABLE_ORDER_COURSE_LIST_OK = 'GET-TABLE-ORDER-COURSE-LIST-OK';
	const GET_TABLE_ORDER_COURSE_LIST_NONE = 'GET-TABLE-ORDER-COURSE-LIST-NONE';
}
class RequestTableOrderCourseResult {
	const REQUEST_TABLE_ORDER_COURSE_OK = 'REQUEST-TABLE-ORDER-COURSE-OK';
	const REQUEST_TABLE_ORDER_COURSE_ALREADY_REQUESTED = 'REQUEST-TABLE-ORDER-COURSE-ALREADY-REQUESTED';
	const REQUEST_TABLE_ORDER_COURSE_FAILED = 'REQUEST-TABLE-ORDER-COURSE-FAILED';
}
class StoreSinglyEftTransactionResult {
	const STORE_SINGLY_EFTTRANSACTION_RESULT_OK = 'STORE-SINGLY-EFTTRANSACTION-RESULT-OK';
	const STORE_SINGLY_EFTTRANSACTION_RESULT_FAILED = 'STORE-SINGLY-EFTTRANSACTION-RESULT-FAILED';
}
class QueueBranchOrderResult {
	const OK = 'QUEUE-BRANCH-ORDER-RESULT-OK';
	const EXT_ORDER_ID_ALREADY_EXISTS = 'QUEUE-BRANCH-ORDER-RESULT-EXT-ORDER-ID-ALREADY-EXISTS';
	const FAILED = 'QUEUE-BRANCH-ORDER-RESULT-FAILED';
}
class PaymentBookingMethod {
	const DEPOSIT = 'PAYMENT-BOOKING-METHOD-DEPOSIT';
	const RECEIPT = 'PAYMENT-BOOKING-METHOD-RECEIPT';
}
class QueueBranchOrderPaymentResult {
	const QUEUE_BRANCH_ORDER_PAYMENT_RESULT_OK = 'QUEUE-BRANCH-ORDER-PAYMENT-RESULT-OK';
	const QUEUE_BRANCH_ORDER_RESULT_RESULT_FAILED = 'QUEUE-BRANCH-ORDER-RESULT-RESULT-FAILED';
}
class QueuedPaymentState {
	const PENDING = 'QUEUED-PAYMENT-STATE-PENDING';
	const OK = 'QUEUED-PAYMENT-STATE-OK';
	const FAILED = 'QUEUED-PAYMENT-STATE-FAILED';
}
class UpdateOrderResult {
	const OK = 'UPDATE-ORDER-RESULT-OK';
	const NOT_FOUND = 'UPDATE-ORDER-RESULT-NOT-FOUND';
	const ORDER_HAS_CHANGED = 'UPDATE-ORDER-RESULT-ORDER-HAS-CHANGED';
	const NO_CHANGES = 'UPDATE-ORDER-RESULT-NO-CHANGES';
	const FAILED = 'UPDATE-ORDER-RESULT-FAILED';
}
class SaveOrderResult {
	const OK = 'SAVE-ORDER-RESULT-OK';
	const NOT_FOUND = 'SAVE-ORDER-RESULT-NOT-FOUND';
	const ORDER_HAS_CHANGED = 'SAVE-ORDER-RESULT-ORDER-HAS-CHANGED';
	const NO_CHANGES = 'SAVE-ORDER-RESULT-NO-CHANGES';
	const FAILED = 'SAVE-ORDER-RESULT-FAILED';
	const EXT_ORDER_ID_ALREADY_EXISTS = 'SAVE-ORDER-RESULT-EXT-ORDER-ID-ALREADY-EXISTS';
}
class GetOrderResult {
	const OK = 'GET-ORDER-RESULT-OK';
	const NOT_FOUND = 'GET-ORDER-RESULT-NOT-FOUND';
}
class PackingSlipState {
	const OPEN = 'PACKING-SLIP-STATE-OPEN';
	const INVOICED = 'PACKING-SLIP-STATE-INVOICED';
	const CANCELLED = 'PACKING-SLIP-STATE-CANCELLED';
}
class PackingSlipType {
	const UNKNOWN = 'PACKING-SLIP-TYPE-UNKNOWN';
	const FROM_INVOICE = 'PACKING-SLIP-TYPE-FROM-INVOICE';
	const PACKING_SLIP = 'PACKING-SLIP-TYPE-PACKING-SLIP';
	const CASH_REGISTER = 'PACKING-SLIP-TYPE-CASH-REGISTER';
}
class SubLineTypeV2 {
	const NONE = 'SUB-LINE-TYPE-V2-NONE';
	const PREPARATION = 'SUB-LINE-TYPE-V2-PREPARATION';
	const COMPONENT = 'SUB-LINE-TYPE-V2-COMPONENT';
	const PERSON_ARTICLE = 'SUB-LINE-TYPE-V2-PERSON-ARTICLE';
	const MEASUREMENT = 'SUB-LINE-TYPE-V2-MEASUREMENT';
	const PREPARATION_COMPONENT = 'SUB-LINE-TYPE-V2-PREPARATION-COMPONENT';
}
class CancelOrderResult {
	const OK = 'CANCEL-ORDER-RESULT-OK';
	const FAILED = 'CANCEL-ORDER-RESULT-FAILED';
	const NOT_FOUND = 'CANCEL-ORDER-RESULT-NOT-FOUND';
	const PENDING = 'CANCEL-ORDER-RESULT-PENDING';
	const ALREADY_CANCELLED = 'CANCEL-ORDER-RESULT-ALREADY-CANCELLED';
}
class PayInvoiceResult {
	const OK = 'PAY-INVOICE-RESULT-OK';
	const FAILED = 'PAY-INVOICE-RESULT-FAILED';
	const PAYMENT_TOO_HIGH = 'PAY-INVOICE-RESULT-PAYMENT-TOO-HIGH';
}
class DeliverOrderResult {
	const OK = 'DELIVER-ORDER-RESULT-OK';
	const ALREADY_DELIVERED = 'DELIVER-ORDER-RESULT-ALREADY-DELIVERED';
	const FAILED = 'DELIVER-ORDER-RESULT-FAILED';
}
class DeliverOrderTurnoverType {
	const INVOICE = 'DELIVER-ORDER-TURNOVER-TYPE-INVOICE';
	const RECEIPT = 'DELIVER-ORDER-TURNOVER-TYPE-RECEIPT';
}
class DeliverOrderV2Result {
	const OK = 'DELIVER-ORDER-V2-RESULT-OK';
	const ALREADY_DELIVERED = 'DELIVER-ORDER-V2-RESULT-ALREADY-DELIVERED';
	const FAILED = 'DELIVER-ORDER-V2-RESULT-FAILED';
}
class ReceiptType {
	const RECEIPT = 'RECEIPT-TYPE-RECEIPT';
	const CREDIT_RECEIPT = 'RECEIPT-TYPE-CREDIT-RECEIPT';
	const CASH_INFLOW = 'RECEIPT-TYPE-CASH-INFLOW';
	const CASH_OUTFLOW = 'RECEIPT-TYPE-CASH-OUTFLOW';
	const PAYMENT_METHOD_TRANSFER = 'RECEIPT-TYPE-PAYMENT-METHOD-TRANSFER';
}
class ReceiptState {
	const OUTSTANDING = 'RECEIPT-STATE-OUTSTANDING';
	const PARTLY_PAID = 'RECEIPT-STATE-PARTLY-PAID';
	const PAID = 'RECEIPT-STATE-PAID';
	const HANDLED = 'RECEIPT-STATE-HANDLED';
}
class GetReceiptResult {
	const OK = 'GET-RECEIPT-RESULT-OK';
	const NOT_FOUND = 'GET-RECEIPT-RESULT-NOT-FOUND';
}
class GetReceiptsByOrderResult {
	const OK = 'GET-RECEIPTS-BY-ORDER-RESULT-OK';
	const NOT_FOUND = 'GET-RECEIPTS-BY-ORDER-RESULT-NOT-FOUND';
}
class GetReceiptsByCashCountResult {
	const OK = 'GET-RECEIPTS-BY-CASH-COUNT-RESULT-OK';
	const NOT_FOUND = 'GET-RECEIPTS-BY-CASH-COUNT-RESULT-NOT-FOUND';
}
class PrintReceiptResult {
	const OK = 'PRINT-RECEIPT-RESULT-OK';
	const NOT_FOUND = 'PRINT-RECEIPT-RESULT-NOT-FOUND';
	const NOT_PRINTED = 'PRINT-RECEIPT-RESULT-NOT-PRINTED';
}
class PrintTableReceiptResult {
	const OK = 'PRINT-TABLE-RECEIPT-RESULT-OK';
	const NOT_FOUND = 'PRINT-TABLE-RECEIPT-RESULT-NOT-FOUND';
	const NOT_PRINTED = 'PRINT-TABLE-RECEIPT-RESULT-NOT-PRINTED';
}
class InvoiceType {
	const INVOICE = 'INVOICE-TYPE-INVOICE';
	const DIRECT_INVOICE = 'INVOICE-TYPE-DIRECT-INVOICE';
	const CREDIT_INVOICE = 'INVOICE-TYPE-CREDIT-INVOICE';
	const REPEATING_INVOICE = 'INVOICE-TYPE-REPEATING-INVOICE';
}
class InvoiceState {
	const OUTSTANDING = 'INVOICE-STATE-OUTSTANDING';
	const PARTLY_PAID = 'INVOICE-STATE-PARTLY-PAID';
	const PAID = 'INVOICE-STATE-PAID';
	const HANDLED = 'INVOICE-STATE-HANDLED';
}
class SaveInvoiceResult {
	const OK = 'SAVE-INVOICE-RESULT-OK';
	const NOT_FOUND = 'SAVE-INVOICE-RESULT-NOT-FOUND';
	const INVOICE_HAS_CHANGED = 'SAVE-INVOICE-RESULT-INVOICE-HAS-CHANGED';
	const FAILED = 'SAVE-INVOICE-RESULT-FAILED';
	const EXT_INVOICE_ID_ALREADY_EXISTS = 'SAVE-INVOICE-RESULT-EXT-INVOICE-ID-ALREADY-EXISTS';
}
class GetInvoiceResult {
	const OK = 'GET-INVOICE-RESULT-OK';
	const NOT_FOUND = 'GET-INVOICE-RESULT-NOT-FOUND';
}
class CreditInvoiceResult {
	const OK = 'CREDIT-INVOICE-RESULT-OK';
	const FAILED = 'CREDIT-INVOICE-RESULT-FAILED';
	const NOT_FOUND = 'CREDIT-INVOICE-RESULT-NOT-FOUND';
}
class JournalFilter {
	const RECEIPT = 'JOURNAL-FILTER-RECEIPT';
	const INVOICE = 'JOURNAL-FILTER-INVOICE';
	const ORDER = 'JOURNAL-FILTER-ORDER';
}
class FinancialGroupType {
	const TURNOVER = 'FINANCIAL-GROUP-TYPE-TURNOVER';
	const PAYMENT = 'FINANCIAL-GROUP-TYPE-PAYMENT';
	const SUSPENSE_ACCOUNT = 'FINANCIAL-GROUP-TYPE-SUSPENSE-ACCOUNT';
	const CASH_INFLOW = 'FINANCIAL-GROUP-TYPE-CASH-INFLOW';
	const CASH_OUTFLOW = 'FINANCIAL-GROUP-TYPE-CASH-OUTFLOW';
	const BPE = 'FINANCIAL-GROUP-TYPE-BPE';
}
class FinancialGroupSource {
	const INVOICE = 'FINANCIAL-GROUP-SOURCE-INVOICE';
	const RECEIPT = 'FINANCIAL-GROUP-SOURCE-RECEIPT';
	const ORDER = 'FINANCIAL-GROUP-SOURCE-ORDER';
}
class UpdateTurnoverGroupsResult {
	const OK = 'UPDATE-TURNOVER-GROUPS-RESULT-OK';
	const FAILED = 'UPDATE-TURNOVER-GROUPS-RESULT-FAILED';
}
class NutritionalCharacteristicPresence {
	const NC_PRESENCE_UNKNOWN = 'NC-PRESENCE-UNKNOWN';
	const NC_PRESENCE_PRESENT = 'NC-PRESENCE-PRESENT';
	const NC_PRESENCE_NOT_PRESENT = 'NC-PRESENCE-NOT-PRESENT';
	const NC_PRESENCE_MAYBE = 'NC-PRESENCE-MAYBE';
}
class NutritionalCharacteristicType {
	const NC_TYPE_ALLERGEN = 'NC-TYPE-ALLERGEN';
	const NC_TYPE_DIET_RESTRICTION = 'NC-TYPE-DIET-RESTRICTION';
}
class CreateProductResult {
	const OK = 'CREATE-PRODUCT-RESULT-OK';
	const FAILED = 'CREATE-PRODUCT-RESULT-FAILED';
	const FAILED_PRODUCT_NUMBER_ALREADY_TAKEN = 'CREATE-PRODUCT-RESULT-FAILED-PRODUCT-NUMBER-ALREADY-TAKEN';
	const FAILED_ARTICLE_NUMBER_ALREADY_TAKEN = 'CREATE-PRODUCT-RESULT-FAILED-ARTICLE-NUMBER-ALREADY-TAKEN';
}
class UpdateProductResult {
	const OK = 'UPDATE-PRODUCT-RESULT-OK';
	const NOT_FOUND = 'UPDATE-PRODUCT-RESULT-NOT-FOUND';
	const NOT_ALLOWED = 'UPDATE-PRODUCT-RESULT-NOT-ALLOWED';
	const FAILED = 'UPDATE-PRODUCT-RESULT-FAILED';
	const FAILED_ARTICLE_NUMBER_ALREADY_TAKEN = 'UPDATE-PRODUCT-RESULT-FAILED-ARTICLE-NUMBER-ALREADY-TAKEN';
}
class GetArticleVariantsResult {
	const OK = 'GET-ARTICLE-VARIANTS-RESULT-OK';
	const FAILED = 'GET-ARTICLE-VARIANTS-RESULT-FAILED';
}
class GetArticlesVariantsResult {
	const OK = 'GET-ARTICLES-VARIANTS-RESULT-OK';
	const FAILED = 'GET-ARTICLES-VARIANTS-RESULT-FAILED';
}
class NewArticleVariantResult {
	const OK = 'NEW-ARTICLE-VARIANT-RESULT-OK';
	const PARENT_NOT_FOUND = 'NEW-ARTICLE-VARIANT-RESULT-PARENT-NOT-FOUND';
	const BEFORE_NOT_FOUND = 'NEW-ARTICLE-VARIANT-RESULT-BEFORE-NOT-FOUND';
	const INSERT_BEFORE_FAILED = 'NEW-ARTICLE-VARIANT-RESULT-INSERT-BEFORE-FAILED';
	const FAILED = 'NEW-ARTICLE-VARIANT-RESULT-FAILED';
}
class UpdateArticleVariantResult {
	const OK = 'UPDATE-ARTICLE-VARIANT-RESULT-OK';
	const VARIANT_NOT_FOUND = 'UPDATE-ARTICLE-VARIANT-RESULT-VARIANT-NOT-FOUND';
	const FAILED = 'UPDATE-ARTICLE-VARIANT-RESULT-FAILED';
}
class DeleteArticleVariantsResult {
	const OK = 'DELETE-ARTICLE-VARIANTS-RESULT-OK';
	const NOT_FOUND = 'DELETE-ARTICLE-VARIANTS-RESULT-NOT-FOUND';
	const FAILED = 'DELETE-ARTICLE-VARIANTS-RESULT-FAILED';
}
class StockHistoryType {
	const API = 'STOCK-HISTORY-TYPE-API';
	const CORRECTION = 'STOCK-HISTORY-TYPE-CORRECTION';
	const DELIVERY = 'STOCK-HISTORY-TYPE-DELIVERY';
	const INTERNAL_DELIVERY = 'STOCK-HISTORY-TYPE-INTERNAL-DELIVERY';
	const INTERNAL_SHIPMENT = 'STOCK-HISTORY-TYPE-INTERNAL-SHIPMENT';
	const MANUAL = 'STOCK-HISTORY-TYPE-MANUAL';
	const SALES = 'STOCK-HISTORY-TYPE-SALES';
	const UNKNOWN = 'STOCK-HISTORY-TYPE-UNKNOWN';
}
class UpdateStockResult {
	const OK = 'UPDATE-STOCK-RESULT-OK';
	const BRANCH_NOT_FOUND = 'UPDATE-STOCK-RESULT-BRANCH-NOT-FOUND';
	const ARTICLE_NOT_FOUND = 'UPDATE-STOCK-RESULT-ARTICLE-NOT-FOUND';
	const NO_STOCK_ARTICLE = 'UPDATE-STOCK-RESULT-NO-STOCK-ARTICLE';
	const FAILED = 'UPDATE-STOCK-RESULT-FAILED';
}
class SetStockResult {
	const OK = 'SET-STOCK-RESULT-OK';
	const BRANCH_NOT_FOUND = 'SET-STOCK-RESULT-BRANCH-NOT-FOUND';
	const ARTICLE_NOT_FOUND = 'SET-STOCK-RESULT-ARTICLE-NOT-FOUND';
	const NO_STOCK_ARTICLE = 'SET-STOCK-RESULT-NO-STOCK-ARTICLE';
	const FAILED = 'SET-STOCK-RESULT-FAILED';
}
class UpdateArticleGroupResult {
	const SAVE_ARTICLE_GROUP_RESULT_OK = 'SAVE-ARTICLE-GROUP-RESULT-OK';
	const SAVE_ARTICLE_GROUP_RESULT_NOT_FOUND = 'SAVE-ARTICLE-GROUP-RESULT-NOT-FOUND';
	const SAVE_ARTICLE_GROUP_RESULT_FAILED = 'SAVE-ARTICLE-GROUP-RESULT-FAILED';
}
class NewArticleGroupResult {
	const OK = 'NEW-ARTICLE-GROUP-RESULT-OK';
	const PARENT_NOTFOUND = 'NEW-ARTICLE-GROUP-RESULT-PARENT-NOTFOUND';
	const FAILED = 'NEW-ARTICLE-GROUP-RESULT-FAILED';
}
class DeleteArticleGroupResult {
	const OK = 'DELETE-ARTICLE-GROUP-RESULT-OK';
	const NOTFOUND = 'DELETE-ARTICLE-GROUP-RESULT-NOTFOUND';
	const FAILED = 'DELETE-ARTICLE-GROUP-RESULT-FAILED';
}
class AddProductsToArticleGroupResult {
	const OK = 'ADD-PRODUCTS-TO-ARTICLE-GROUP-RESULT-OK';
	const NOT_FOUND = 'ADD-PRODUCTS-TO-ARTICLE-GROUP-RESULT-NOT-FOUND';
	const FAILED = 'ADD-PRODUCTS-TO-ARTICLE-GROUP-RESULT-FAILED';
}
class ReplaceProductsOfArticleGroupResult {
	const OK = 'REPLACE-PRODUCTS-OF-ARTICLE-GROUP-RESULT-OK';
	const NOT_FOUND = 'REPLACE-PRODUCTS-OF-ARTICLE-GROUP-RESULT-NOT-FOUND';
	const FAILED = 'REPLACE-PRODUCTS-OF-ARTICLE-GROUP-RESULT-FAILED';
}
class DeleteProductsFromArticleGroupResult {
	const OK = 'DELETE-PRODUCTS-FROM-ARTICLE-GROUP-RESULT-OK';
	const NOT_FOUND = 'DELETE-PRODUCTS-FROM-ARTICLE-GROUP-RESULT-NOT-FOUND';
	const FAILED = 'DELETE-PRODUCTS-FROM-ARTICLE-GROUP-RESULT-FAILED';
}
class MessageType {
	const INFO = 'MESSAGE-TYPE-INFO';
	const OK = 'MESSAGE-TYPE-OK';
	const WARNING = 'MESSAGE-TYPE-WARNING';
}
class PurchaseOrderState {
	const OPEN = 'PURCHASE-ORDER-STATE-OPEN';
	const WAIT_FOR_APPROVAL = 'PURCHASE-ORDER-STATE-WAIT-FOR-APPROVAL';
	const SUPPLIER_SUBMITTED = 'PURCHASE-ORDER-STATE-SUPPLIER-SUBMITTED';
	const SUPPLIER_RECEIVED = 'PURCHASE-ORDER-STATE-SUPPLIER-RECEIVED';
	const SUPPLIER_INPROGRESS = 'PURCHASE-ORDER-STATE-SUPPLIER-INPROGRESS';
	const SUPPLIER_SHIPPED = 'PURCHASE-ORDER-STATE-SUPPLIER-SHIPPED';
	const PARTIALLY_DELIVERED = 'PURCHASE-ORDER-STATE-PARTIALLY-DELIVERED';
	const COMPLETELY_DELIVERED = 'PURCHASE-ORDER-STATE-COMPLETELY-DELIVERED';
	const CANCELLED = 'PURCHASE-ORDER-STATE-CANCELLED';
	const PARTIALLY_CANCELLED = 'PURCHASE-ORDER-STATE-PARTIALLY-CANCELLED';
}
class SavePurchaseOrderResult {
	const OK = 'SAVE-PURCHASE-ORDER-RESULT-OK';
	const NOT_FOUND = 'SAVE-PURCHASE-ORDER-RESULT-NOT-FOUND';
	const ORDER_HAS_CHANGED = 'SAVE-PURCHASE-ORDER-RESULT-ORDER-HAS-CHANGED';
	const FAILED = 'SAVE-PURCHASE-ORDER-RESULT-FAILED';
	const EXT_ORDER_ID_ALREADY_EXISTS = 'SAVE-PURCHASE-ORDER-RESULT-EXT-ORDER-ID-ALREADY-EXISTS';
	const DELIVERY_ADDRESS_REQUIRED = 'SAVE-PURCHASE-ORDER-RESULT-DELIVERY-ADDRESS-REQUIRED';
}
class SavePurchaseDeliveryResult {
	const OK = 'SAVE-PURCHASE-DELIVERY-RESULT-OK';
	const NOT_FOUND = 'SAVE-PURCHASE-DELIVERY-RESULT-NOT-FOUND';
	const DELIVERY_HAS_CHANGED = 'SAVE-PURCHASE-DELIVERY-RESULT-DELIVERY-HAS-CHANGED';
	const FAILED = 'SAVE-PURCHASE-DELIVERY-RESULT-FAILED';
	const EXT_DELIVERY_ID_ALREADY_EXISTS = 'SAVE-PURCHASE-DELIVERY-RESULT-EXT-DELIVERY-ID-ALREADY-EXISTS';
	const ORDER_NOT_FOUND = 'SAVE-PURCHASE-DELIVERY-RESULT-ORDER-NOT-FOUND';
	const ORDER_HAS_CHANGED = 'SAVE-PURCHASE-DELIVERY-RESULT-ORDER-HAS-CHANGED';
	const LINES_DIVERGE_FROM_ORDER = 'SAVE-PURCHASE-DELIVERY-RESULT-LINES-DIVERGE-FROM-ORDER';
	const DELIVERY_ADDRESS_REQUIRED = 'SAVE-PURCHASE-DELIVERY-RESULT-DELIVERY-ADDRESS-REQUIRED';
}
class CardLayoutFieldType {
	const DATABASE = 'CARD-LAYOUT-FIELD-TYPE-DATABASE';
	const CALCULATED_VIRTUAL = 'CARD-LAYOUT-FIELD-TYPE-CALCULATED-VIRTUAL';
	const CALCULATED_PERMANENT = 'CARD-LAYOUT-FIELD-TYPE-CALCULATED-PERMANENT';
	const EXTERNAL = 'CARD-LAYOUT-FIELD-TYPE-EXTERNAL';
	const LABEL = 'CARD-LAYOUT-FIELD-TYPE-LABEL';
	const UNKNOWN = 'CARD-LAYOUT-FIELD-TYPE-UNKNOWN';
}
class UpdateArticleCardLayoutResult {
	const OK = 'UPDATE-ARTICLE-CARD-LAYOUT-RESULT-OK';
	const FAILED = 'UPDATE-ARTICLE-CARD-LAYOUT-RESULT-FAILED';
}
class GetRetailSpaceRentalResult {
	const OK = 'GET-RETAIL-SPACE-RENTAL-RESULT-OK';
	const NOT_FOUND = 'GET-RETAIL-SPACE-RENTAL-RESULT-NOT-FOUND';
}
class InterbranchOrderState {
	const OPEN = 'INTERBRANCH-ORDER-STATE-OPEN';
	const PARTIALLY_SENT = 'INTERBRANCH-ORDER-STATE-PARTIALLY-SENT';
	const COMPLETELY_SENT = 'INTERBRANCH-ORDER-STATE-COMPLETELY-SENT';
	const PARTIALLY_CANCELLED = 'INTERBRANCH-ORDER-STATE-PARTIALLY-CANCELLED';
	const COMPLETELY_CANCELLED = 'INTERBRANCH-ORDER-STATE-COMPLETELY-CANCELLED';
}
class CreateInterbranchOrderResult {
	const OK = 'CREATE-INTERBRANCH-ORDER-RESULT-OK';
	const FAILED = 'CREATE-INTERBRANCH-ORDER-RESULT-FAILED';
}
class ClaimInterbranchOrderResult {
	const OK = 'CLAIM-INTERBRANCH-ORDER-RESULT-OK';
	const CLAIMED_BY_OTHER_WORKPLACE = 'CLAIM-INTERBRANCH-ORDER-RESULT-CLAIMED-BY-OTHER-WORKPLACE';
	const NOT_FOUND = 'CLAIM-INTERBRANCH-ORDER-RESULT-NOT-FOUND';
	const WORKPLACE_NOT_FOUND = 'CLAIM-INTERBRANCH-ORDER-RESULT-WORKPLACE-NOT-FOUND';
	const FAILED = 'CLAIM-INTERBRANCH-ORDER-RESULT-FAILED';
}
class ReleaseInterbranchOrderResult {
	const OK = 'RELEASE-INTERBRANCH-ORDER-RESULT-OK';
	const NOT_CLAIMED = 'RELEASE-INTERBRANCH-ORDER-RESULT-NOT-CLAIMED';
	const NOT_FOUND = 'RELEASE-INTERBRANCH-ORDER-RESULT-NOT-FOUND';
	const FAILED = 'RELEASE-INTERBRANCH-ORDER-RESULT-FAILED';
}
class InterbranchShipmentState {
	const OPEN = 'INTERBRANCH-SHIPMENT-STATE-OPEN';
	const PARTIALLY_DELIVERED = 'INTERBRANCH-SHIPMENT-STATE-PARTIALLY-DELIVERED';
	const COMPLETELY_DELIVERED = 'INTERBRANCH-SHIPMENT-STATE-COMPLETELY-DELIVERED';
	const PARTIALLY_CANCELLED = 'INTERBRANCH-SHIPMENT-STATE-PARTIALLY-CANCELLED';
	const COMPLETELY_CANCELLED = 'INTERBRANCH-SHIPMENT-STATE-COMPLETELY-CANCELLED';
	const PARTIALLY_DELIVERED_PARTIALLY_CANCELLED = 'INTERBRANCH-SHIPMENT-STATE-PARTIALLY-DELIVERED-PARTIALLY-CANCELLED';
	const COMPLETELY_DELIVERED_PARTIALLY_CANCELLED = 'INTERBRANCH-SHIPMENT-STATE-COMPLETELY-DELIVERED-PARTIALLY-CANCELLED';
}
class ShipInterbranchOrderResult {
	const OK = 'SHIP-INTERBRANCH-ORDER-RESULT-OK';
	const NOT_CLAIMED = 'SHIP-INTERBRANCH-ORDER-RESULT-NOT-CLAIMED';
	const CLAIMED_BY_OTHER_WORKPLACE = 'SHIP-INTERBRANCH-ORDER-RESULT-CLAIMED-BY-OTHER-WORKPLACE';
	const NOT_FOUND = 'SHIP-INTERBRANCH-ORDER-RESULT-NOT-FOUND';
	const FAILED = 'SHIP-INTERBRANCH-ORDER-RESULT-FAILED';
	const FAILED_ALL_SEND = 'SHIP-INTERBRANCH-ORDER-RESULT-FAILED-ALL-SEND';
	const FAILED_ORDER_CANCELLED = 'SHIP-INTERBRANCH-ORDER-RESULT-FAILED-ORDER-CANCELLED';
}
class DeliverInterbranchShipmentResult {
	const OK = 'DELIVER-INTERBRANCH-SHIPMENT-RESULT-OK';
	const NOT_FOUND = 'DELIVER-INTERBRANCH-SHIPMENT-RESULT-NOT-FOUND';
	const FAILED = 'DELIVER-INTERBRANCH-SHIPMENT-RESULT-FAILED';
}
class CreateInterbranchShipmentResult {
	const OK = 'CREATE-INTERBRANCH-SHIPMENT-RESULT-OK';
	const FAILED = 'CREATE-INTERBRANCH-SHIPMENT-RESULT-FAILED';
}
class CreateInterbranchDeliveryResult {
	const OK = 'CREATE-INTERBRANCH-DELIVERY-RESULT-OK';
	const FAILED = 'CREATE-INTERBRANCH-DELIVERY-RESULT-FAILED';
}
class ns_EidType {
	const EID_TYPE_MIFARE = 'EID-TYPE-MIFARE';
}
class ns_EntityType {
	const ENTITY_TYPE_UNKNOWN = 'ENTITY-TYPE-UNKNOWN';
	const ENTITY_TYPE_EMPLOYEE = 'ENTITY-TYPE-EMPLOYEE';
	const ENTITY_TYPE_RELATION = 'ENTITY-TYPE-RELATION';
}
class VerifyResult {
	const AUTHENTICATED = 'VERIFY-RESULT-AUTHENTICATED';
	const NOT_AUTHENTICATED = 'VERIFY-RESULT-NOT-AUTHENTICATED';
	const ACCOUNT_LOCKED = 'VERIFY-RESULT-ACCOUNT-LOCKED';
	const _2FA_REQUIRED = 'VERIFY-RESULT-2FA-REQUIRED';
	const PASSWORD_CHANGE_REQUIRED = 'VERIFY-RESULT-PASSWORD-CHANGE-REQUIRED';
}
class SaveCredentialsResult {
	const OK = 'SAVE-CREDENTIALS-RESULT-OK';
	const NO_AUTHORIZATION = 'SAVE-CREDENTIALS-RESULT-NO-AUTHORIZATION';
	const PASSWORD_FAILS_REQUIREMENT = 'SAVE-CREDENTIALS-RESULT-PASSWORD-FAILS-REQUIREMENT';
	const PASSWORD_REUSE_NOT_ALLOWED = 'SAVE-CREDENTIALS-RESULT-PASSWORD-REUSE-NOT-ALLOWED';
}
class OverviewFilterOperator {
	const EQUAL = 'EQUAL';
	const LIKE = 'LIKE';
	const BIGGER = 'BIGGER';
	const SMALLER = 'SMALLER';
	const NOTEQUAL = 'NOTEQUAL';
	const ISNULL = 'ISNULL';
	const ISNOTNULL = 'ISNOTNULL';
	const CONTAINS = 'CONTAINS';
	const OVERLAP = 'OVERLAP';
	const IS = 'IS';
	const OVERLAPORNONE = 'OVERLAPORNONE';
	const INCOLLECTION = 'INCOLLECTION';
}
class SortOrderType {
	const ASCENDING = 'ASCENDING';
	const DESCENDING = 'DESCENDING';
}
class OverviewImageDetails {
	const NONE = 'OVERVIEW-IMAGE-DETAILS-NONE';
	const SIMPLE = 'OVERVIEW-IMAGE-DETAILS-SIMPLE';
}
class GetOverviewResult {
	const OK = 'GET-OVERVIEW-RESULT-OK';
	const FAILED = 'GET-OVERVIEW-RESULT-FAILED';
}
class GetOverviewErrorCode {
	const GET_OVERVIEW_ERROR_INVALID_TYPE = 'GET-OVERVIEW-ERROR-INVALID-TYPE';
	const GET_OVERVIEW_ERROR_INVALID_CATEGORYID = 'GET-OVERVIEW-ERROR-INVALID-CATEGORYID';
	const GET_OVERVIEW_ERROR_INVALID_SELECT_FIELD = 'GET-OVERVIEW-ERROR-INVALID-SELECT-FIELD';
	const GET_OVERVIEW_ERROR_INVALID_FILTER_FIELD = 'GET-OVERVIEW-ERROR-INVALID-FILTER-FIELD';
	const GET_OVERVIEW_ERROR_INVALID_FILTER_OPERATOR = 'GET-OVERVIEW-ERROR-INVALID-FILTER-OPERATOR';
	const GET_OVERVIEW_ERROR_INVALID_ORDER_FIELD = 'GET-OVERVIEW-ERROR-INVALID-ORDER-FIELD';
}
class GetOverviewFieldsResult {
	const OK = 'GET-OVERVIEW-FIELDS-RESULT-OK';
	const FAILED = 'GET-OVERVIEW-FIELDS-RESULT-FAILED';
}
class GetOverviewFieldsErrorCode {
	const GET_OVERVIEW_FIELDS_ERROR_INVALID_TYPE = 'GET-OVERVIEW-FIELDS-ERROR-INVALID-TYPE';
	const GET_OVERVIEW_FIELDS_ERROR_INVALID_CATEGORYID = 'GET-OVERVIEW-FIELDS-ERROR-INVALID-CATEGORYID';
}
class UpdateBatchResult {
	const OK = 'UPDATE-BATCH-RESULT-OK';
	const FAILED = 'UPDATE-BATCH-RESULT-FAILED';
	const WARNINGS = 'UPDATE-BATCH-RESULT-WARNINGS';
}
class UpdateBatchErrorCode {
	const UPDATE_BATCH_ERROR_INVALID_TYPE = 'UPDATE-BATCH-ERROR-INVALID-TYPE';
	const UPDATE_BATCH_ERROR_NO_NUMBERS = 'UPDATE-BATCH-ERROR-NO-NUMBERS';
	const UPDATE_BATCH_ERROR_NO_FIELDS = 'UPDATE-BATCH-ERROR-NO-FIELDS';
	const UPDATE_BATCH_ERROR_INVALID_CATEGORYID = 'UPDATE-BATCH-ERROR-INVALID-CATEGORYID';
	const UPDATE_BATCH_ERROR_INVALID_NUMBER = 'UPDATE-BATCH-ERROR-INVALID-NUMBER';
	const UPDATE_BATCH_ERROR_INVALID_FIELD = 'UPDATE-BATCH-ERROR-INVALID-FIELD';
	const UPDATE_BATCH_ERROR_FIELD_LENGTH = 'UPDATE-BATCH-ERROR-FIELD-LENGTH';
	const UPDATE_BATCH_ERROR_FIELD_READONLY = 'UPDATE-BATCH-ERROR-FIELD-READONLY';
	const UPDATE_BATCH_ERROR_FIELD_REQUIRED = 'UPDATE-BATCH-ERROR-FIELD-REQUIRED';
	const UPDATE_BATCH_ERROR_FIELD_NOT_ACTIVE = 'UPDATE-BATCH-ERROR-FIELD-NOT-ACTIVE';
	const UPDATE_BATCH_ERROR_FIELD_NOT_ON_LAYOUT = 'UPDATE-BATCH-ERROR-FIELD-NOT-ON-LAYOUT';
	const UPDATE_BATCH_ERROR_FIELD_SELECTVALUE_INVALID = 'UPDATE-BATCH-ERROR-FIELD-SELECTVALUE-INVALID';
	const UPDATE_BATCH_ERROR_FIELD_NULL = 'UPDATE-BATCH-ERROR-FIELD-NULL';
	const UPDATE_BATCH_ERROR_FIELD_TYPE_INCORRECT = 'UPDATE-BATCH-ERROR-FIELD-TYPE-INCORRECT';
	const UPDATE_BATCH_ERROR_PROCESSING_ERROR = 'UPDATE-BATCH-ERROR-PROCESSING-ERROR';
}
class AuthorLevel {
	const NONE = 'AUTHOR-LEVEL-NONE';
	const BUDDY = 'AUTHOR-LEVEL-BUDDY';
	const FULL = 'AUTHOR-LEVEL-FULL';
}
class UpdateBehavior {
	const APPEND = 'UPDATE-BEHAVIOR-APPEND';
	const REPLACE = 'UPDATE-BEHAVIOR-REPLACE';
}
class PrintResult {
	const OK = 'PRINT-RESULT-OK';
	const PRINTER_NOT_FOUND = 'PRINT-RESULT-PRINTER-NOT-FOUND';
	const NO_PRINTER_INSTALLED = 'PRINT-RESULT-NO-PRINTER-INSTALLED';
	const NOT_PRINTED = 'PRINT-RESULT-NOT-PRINTED';
}
class KitchenTicketState {
	const NOT_STARTED = 'KITCHEN-TICKET-STATE-NOT-STARTED';
	const STARTED = 'KITCHEN-TICKET-STATE-STARTED';
	const COMPLETED = 'KITCHEN-TICKET-STATE-COMPLETED';
	const DELETED = 'KITCHEN-TICKET-STATE-DELETED';
}
class StockCorrectionType {
	const CORRECTION_TYPE_COUNT = 'CORRECTION-TYPE-COUNT';
	const CORRECTION_TYPE_WRITE_OFF = 'CORRECTION-TYPE-WRITE-OFF';
}
class StockCorrectionMode {
	const ABSOLUTE = 'STOCK-CORRECTION-MODE-ABSOLUTE';
	const RELATIVE = 'STOCK-CORRECTION-MODE-RELATIVE';
}
class SaveStockCorrectionsResult {
	const OK = 'SAVE-STOCK-CORRECTIONS-RESULT-OK';
	const BRANCH_NOT_FOUND = 'SAVE-STOCK-CORRECTIONS-RESULT-BRANCH-NOT-FOUND';
	const ARTICLE_NOT_FOUND = 'SAVE-STOCK-CORRECTIONS-RESULT-ARTICLE-NOT-FOUND';
	const NO_STOCK_ARTICLE = 'SAVE-STOCK-CORRECTIONS-RESULT-NO-STOCK-ARTICLE';
	const NO_CORRECTIONS = 'SAVE-STOCK-CORRECTIONS-RESULT-NO-CORRECTIONS';
	const DUPLICATE_ARTICLE = 'SAVE-STOCK-CORRECTIONS-RESULT-DUPLICATE-ARTICLE';
	const FAILED = 'SAVE-STOCK-CORRECTIONS-RESULT-FAILED';
}
class GetPurchaseBookResult {
	const OK = 'GET-PURCHASE-BOOK-RESULT-OK';
}
class SavePurchaseBookResult {
	const OK = 'SAVE-PURCHASE-BOOK-RESULT-OK';
}
class AddToPurchaseBookResult {
	const OK = 'ADD-TO-PURCHASE-BOOK-RESULT-OK';
}
class GetArticlesNutritionalCharacteristicsResult {
	const OK = 'GET-ARTICLES-NUTRITIONAL-CHARACTERISTICS-RESULT-OK';
	const FAILED = 'GET-ARTICLES-NUTRITIONAL-CHARACTERISTICS-RESULT-FAILED';
}
class UpdateArticleNutritionalCharacteristicsResult {
	const OK = 'UPDATE-ARTICLE-NUTRITIONAL-CHARACTERISTICS-RESULT-OK';
	const FAILED = 'UPDATE-ARTICLE-NUTRITIONAL-CHARACTERISTICS-RESULT-FAILED';
}
class SubLineType {
	const NO_SUB_LINE = 'SUB-LINE-TYPE-NO-SUB-LINE';
	const PREPARATION_METHOD = 'SUB-LINE-TYPE-PREPARATION-METHOD';
	const COMPONENT_LINE = 'SUB-LINE-TYPE-COMPONENT-LINE';
	const PERSONAL_ARTICLE = 'SUB-LINE-TYPE-PERSONAL-ARTICLE';
	const DIMENSION_CALCULATION_ARTICLE = 'SUB-LINE-TYPE-DIMENSION-CALCULATION-ARTICLE';
}
class GetPreparationMethodGroupsResult {
	const OK = 'GET-PREPARATION-METHOD-GROUPS-RESULT-OK';
}
class DeletePreparationMethodGroupResult {
	const OK = 'DELETE-PREPARATION-METHOD-GROUP-RESULT-OK';
	const FAILED = 'DELETE-PREPARATION-METHOD-GROUP-RESULT-FAILED';
	const FAILED_STILL_IN_USE = 'DELETE-PREPARATION-METHOD-GROUP-RESULT-FAILED-STILL-IN-USE';
}
class GetArticlesPreparationMethodGroupsResult {
	const OK = 'GET-ARTICLES-PREPARATION-METHOD-GROUPS-RESULT-OK';
}
class UpdateArticlePreparationMethodGroupsResult {
	const OK = 'UPDATE-ARTICLE-PREPARATION-METHOD-GROUPS-RESULT-OK';
	const FAILED = 'UPDATE-ARTICLE-PREPARATION-METHOD-GROUPS-RESULT-FAILED';
}
class PlaceTableOrderResult {
	const OK = 'PLACE-TABLE-ORDER-RESULT-OK';
	const IDENTIFIER_FAILED = 'PLACE-TABLE-ORDER-RESULT-IDENTIFIER-FAILED';
	const LINES_FAILED = 'PLACE-TABLE-ORDER-RESULT-LINES-FAILED';
	const PAYMENTS_FAILED = 'PLACE-TABLE-ORDER-RESULT-PAYMENTS-FAILED';
}
class LinesResult {
	const NOTHING = 'LINES-RESULT-NOTHING';
	const ORDER_CREATED = 'LINES-RESULT-ORDER-CREATED';
	const ORDER_UPDATED = 'LINES-RESULT-ORDER-UPDATED';
}
class PaymentsResult {
	const NOTHING = 'PAYMENTS-RESULT-NOTHING';
	const RECEIPT_CREATED = 'PAYMENTS-RESULT-RECEIPT-CREATED';
	const ORDER_PREPAID_BECAUSE_UNDERPAID = 'PAYMENTS-RESULT-ORDER-PREPAID-BECAUSE-UNDERPAID';
	const ORDER_PREPAID_BECAUSE_OVERPAID = 'PAYMENTS-RESULT-ORDER-PREPAID-BECAUSE-OVERPAID';
}
class ChangeTablePropertyResult {
	const OK = 'CHANGE-TABLE-PROPERTY-RESULT-OK';
	const FAILED = 'CHANGE-TABLE-PROPERTY-RESULT-FAILED';
}
class TodoListCategory {
	const GENERIC = 'TODO-LIST-CATEGORY-GENERIC';
	const PURCHASE = 'TODO-LIST-CATEGORY-PURCHASE';
	const SALES = 'TODO-LIST-CATEGORY-SALES';
	const STOCK = 'TODO-LIST-CATEGORY-STOCK';
}
class SaveAuthorizationGroupResult {
	const OK = 'SAVE-AUTHORIZATION-GROUP-RESULT-OK';
	const FAILED = 'SAVE-AUTHORIZATION-GROUP-RESULT-FAILED';
}
class DeleteAuthorizationGroupResult {
	const OK = 'DELETE-AUTHORIZATION-GROUP-RESULT-OK';
	const FAILED = 'DELETE-AUTHORIZATION-GROUP-RESULT-FAILED';
}
class UpdateEmployeeAuthorizationGroupsResult {
	const OK = 'UPDATE-EMPLOYEE-AUTHORIZATION-GROUPS-RESULT-OK';
	const FAILED = 'UPDATE-EMPLOYEE-AUTHORIZATION-GROUPS-RESULT-FAILED';
}
class SavePreparationMethodGroupResult {
	const OK = 'SAVE-PREPARATION-METHOD-GROUP-RESULT-OK';
	const FAILED = 'SAVE-PREPARATION-METHOD-GROUP-RESULT-FAILED';
}
class NutritionalCharacteristicsType {
	const NUTRITIONAL_TYPE_PRODUCT = 'NUTRITIONAL-TYPE-PRODUCT';
	const NUTRITIONAL_TYPE_RELATION = 'NUTRITIONAL-TYPE-RELATION';
}
class GetNutritionalCharacteristicsResult {
	const OK = 'GET-NUTRITIONAL-CHARACTERISTICS-RESULT-OK';
	const FAILED = 'GET-NUTRITIONAL-CHARACTERISTICS-RESULT-FAILED';
}
class UpdateNutritionalCharacteristicsResult {
	const OK = 'UPDATE-NUTRITIONAL-CHARACTERISTICS-RESULT-OK';
	const FAILED = 'UPDATE-NUTRITIONAL-CHARACTERISTICS-RESULT-FAILED';
}
class SetRelationPresenceResult {
	const OK = 'SET-RELATION-PRESENCE-RESULT-OK';
	const OK_RELATION_HAS_OUTSTANDING_BALANCE = 'SET-RELATION-PRESENCE-RESULT-OK-RELATION-HAS-OUTSTANDING-BALANCE';
	const FAILED = 'SET-RELATION-PRESENCE-RESULT-FAILED';
}
class GetRelationPresenceResponseResult {
	const GET_RELATION_PRESENCE_RESULT_RELATION_PRESENCE_FOUND = 'GET-RELATION-PRESENCE-RESULT-RELATION-PRESENCE-FOUND';
	const GET_RELATION_PRESENCE_RESULT_RELATION_PRESENCE_NOT_FOUND = 'GET-RELATION-PRESENCE-RESULT-RELATION-PRESENCE-NOT-FOUND';
}
class SaveArticleBranchDeviationsResponseResult {
	const SAVE_ARTICLE_BRANCH_DEVIATION_RESULT_OK = 'SAVE-ARTICLE-BRANCH-DEVIATION-RESULT-OK';
	const SAVE_ARTICLE_BRANCH_DEVIATION_RESULT_FAILED = 'SAVE-ARTICLE-BRANCH-DEVIATION-RESULT-FAILED';
}
class UpdateArticleNutrientsResponseResult {
	const UPDATE_ARTICLE_NUTRIENTS_RESULT_OK = 'UPDATE-ARTICLE-NUTRIENTS-RESULT-OK';
	const UPDATE_ARTICLE_NUTRIENTS_RESULT_ERROR = 'UPDATE-ARTICLE-NUTRIENTS-RESULT-ERROR';
}
class CreateInvoiceFromPackingSlipsResponseResult {
	const CREATE_INVOICE_FROM_PACKING_SLIPS_OK = 'CREATE-INVOICE-FROM-PACKING-SLIPS-OK';
	const CREATE_INVOICE_FROM_PACKING_SLIPS_CANT_COMBINE_PACKING_SLIPS = 'CREATE-INVOICE-FROM-PACKING-SLIPS-CANT-COMBINE-PACKING-SLIPS';
	const CREATE_INVOICE_FROM_PACKING_SLIPS_ISSUANCE_SETTLED_WITH_RELATION_POINTS = 'CREATE-INVOICE-FROM-PACKING-SLIPS-ISSUANCE-SETTLED-WITH-RELATION-POINTS';
	const CREATE_INVOICE_FROM_PACKING_SLIPS_RELATION_CREDIT_LIMIT_REACHED = 'CREATE-INVOICE-FROM-PACKING-SLIPS-RELATION-CREDIT-LIMIT-REACHED';
	const CREATE_INVOICE_FROM_PACKING_SLIPS_ALREADY_INVOICED = 'CREATE-INVOICE-FROM-PACKING-SLIPS-ALREADY-INVOICED';
	const CREATE_INVOICE_FROM_PACKING_SLIPS_PACKING_SLIPS_DIFFERENT_ACTIVITIES = 'CREATE-INVOICE-FROM-PACKING-SLIPS-PACKING-SLIPS-DIFFERENT-ACTIVITIES';
}
class ConfigurationPer {
	const GLOBAL = 'CONFIGURATION-PER-GLOBAL';
	const BRANCH = 'CONFIGURATION-PER-BRANCH';
	const WORKPLACE = 'CONFIGURATION-PER-WORKPLACE';
}
class UpdateConfigurationResult {
	const OK = 'UPDATE-CONFIGURATION-RESULT-OK';
	const FAILED = 'UPDATE-CONFIGURATION-RESULT-FAILED';
}
class UpdateConfigurationValuesResult {
	const OK = 'UPDATE-CONFIGURATION-VALUES-RESULT-OK';
	const FAILED = 'UPDATE-CONFIGURATION-VALUES-RESULT-FAILED';
}
class ButtonLayout_GroupPosition {
	const TOP = 'Top';
	const RIGHT = 'Right';
}
class ButtonLayoutTabKind {
	const FIXED_LAYOUT = 'BUTTON-LAYOUT-TAB-KIND-FIXED-LAYOUT';
	const BRANCH_LAYOUT = 'BUTTON-LAYOUT-TAB-KIND-BRANCH-LAYOUT';
	const MEALPLAN = 'BUTTON-LAYOUT-TAB-KIND-MEALPLAN';
}
class GetButtonLayoutGroupDetailsResult {
	const OK = 'GET-BUTTON-LAYOUT-GROUP-DETAILS-RESULT-OK';
	const FAILED = 'GET-BUTTON-LAYOUT-GROUP-DETAILS-RESULT-FAILED';
}
class SaveButtonLayoutGroupDetailsResult {
	const OK = 'SAVE-BUTTON-LAYOUT-GROUP-DETAILS-RESULT-OK';
	const FAILED = 'SAVE-BUTTON-LAYOUT-GROUP-DETAILS-RESULT-FAILED';
}
class DeleteButtonLayoutGroupResult {
	const OK = 'DELETE-BUTTON-LAYOUT-GROUP-RESULT-OK';
	const FAILED = 'DELETE-BUTTON-LAYOUT-GROUP-RESULT-FAILED';
}
class AssignButtonLayoutGroupToWorkplacesResult {
	const OK = 'ASSIGN-BUTTON-LAYOUT-GROUP-TO-WORKPLACES-RESULT-OK';
	const FAILED = 'ASSIGN-BUTTON-LAYOUT-GROUP-TO-WORKPLACES-RESULT-FAILED';
}
class SaveDayStockConfigurationResult {
	const OK = 'SAVE-DAY-STOCK-CONFIGURATION-RESULT-OK';
}
class SaveActivityTypesResult {
	const OK = 'SAVE-ACTIVITY-TYPES-RESULT-OK';
	const FAILED = 'SAVE-ACTIVITY-TYPES-RESULT-FAILED';
}
class CreateActivityResult {
	const OK = 'CREATE-ACTIVITY-RESULT-OK';
	const FAILED = 'CREATE-ACTIVITY-RESULT-FAILED';
}
class UpdateActivityResult {
	const OK = 'UPDATE-ACTIVITY-RESULT-OK';
	const NOT_FOUND = 'UPDATE-ACTIVITY-RESULT-NOT-FOUND';
	const FAILED = 'UPDATE-ACTIVITY-RESULT-FAILED';
}
class SaveActivityResult {
	const OK = 'SAVE-ACTIVITY-RESULT-OK';
	const NOT_FOUND = 'SAVE-ACTIVITY-RESULT-NOT-FOUND';
	const FAILED = 'SAVE-ACTIVITY-RESULT-FAILED';
}
class DeleteActivityResult {
	const OK = 'DELETE-ACTIVITY-RESULT-OK';
	const NOT_FOUND = 'DELETE-ACTIVITY-RESULT-NOT-FOUND';
	const FAILED = 'DELETE-ACTIVITY-RESULT-FAILED';
}
class MealplanArticleGroupType {
	const ARTICLEGROUP_TYPE_FIXED = 'ARTICLEGROUP-TYPE-FIXED';
	const ARTICLEGROUP_TYPE_SELECTION = 'ARTICLEGROUP-TYPE-SELECTION';
	const ARTICLEGROUP_TYPE_UNKOWN = 'ARTICLEGROUP-TYPE-UNKOWN';
}
class GetScheduledMealPlansResult {
	const GET_SCHEDULED_MEALPLAN_RESULT_OK = 'GET-SCHEDULED-MEALPLAN-RESULT-OK';
	const GET_SCHEDULED_MEALPLAN_RESULT_NO_DATA = 'GET-SCHEDULED-MEALPLAN-RESULT-NO-DATA';
}
class ArticleAlterationsGroupType {
	const ALL = 'ALL';
	const PREPARATION = 'PREPARATION';
	const CROSS_SELL = 'CROSS-SELL';
	const REPLACEMENT = 'REPLACEMENT';
	const MENU = 'MENU';
}
class SaveArticleAlterationsGroupResult {
	const OK = 'OK';
	const ALTERATION_ALREADY_EXISTS = 'ALTERATION-ALREADY-EXISTS';
}
class DeleteArticleAlterationsGroupResult {
	const OK = 'OK';
	const STILL_IN_USE = 'STILL-IN-USE';
}
class UpdateAttachedArticleAlterationsGroupsResult {
	const OK = 'OK';
}
class UpdateArticleMenuResult {
	const OK = 'OK';
	const COULDNT_SAVE = 'COULDNT-SAVE';
	const NOT_ALL_ARTICLE_SETTINGS_SAVED = 'NOT-ALL-ARTICLE-SETTINGS-SAVED';
}
class UpdateOnlineAuthorizationTreeResult {
	const OK = 'OK';
	const AUTHORIZATION_REMOVED = 'AUTHORIZATION-REMOVED';
}
class SlaveApiType {
	const NO_SLAVE_API = 'NO-SLAVE-API';
	const BRANCH_SLAVE_API = 'BRANCH-SLAVE-API';
	const WORKPLACE_SLAVE_API = 'WORKPLACE-SLAVE-API';
}
class RegisterTerminalResult {
	const OK = 'REGISTER-TERMINAL-RESULT-OK';
	const REGISTERED = 'REGISTER-TERMINAL-RESULT-REGISTERED';
	const UNKNOWN = 'REGISTER-TERMINAL-RESULT-UNKNOWN';
}
class CondenseLines {
	const OFF = 'CONDENSE-LINES-OFF';
	const LAST_LINE = 'CONDENSE-LINES-LAST-LINE';
	const FULL = 'CONDENSE-LINES-FULL';
}
class UnknownTableAction {
	const UNKNOWN_TABLE_ALLOW = 'UNKNOWN-TABLE-ALLOW';
	const UNKNOWN_TABLE_WARNING = 'UNKNOWN-TABLE-WARNING';
	const UNKNOWN_TABLE_BLOCK = 'UNKNOWN-TABLE-BLOCK';
}
class DayStockBehaviour {
	const ASK_CONFIRMATION = 'DAY-STOCK-BEHAVIOUR-ASK-CONFIRMATION';
	const BLOCK = 'DAY-STOCK-BEHAVIOUR-BLOCK';
}
class GetBranchInformationResult {
	const OK = 'GET-BRANCH-INFORMATION-RESULT-OK';
	const FAILED = 'GET-BRANCH-INFORMATION-RESULT-FAILED';
}
class CreateDeliveryMethodResult {
	const OK = 'CREATE-DELIVERY-METHOD-RESULT-OK';
	const FAILED = 'CREATE-DELIVERY-METHOD-RESULT-FAILED';
	const ALREADY_EXISTS = 'CREATE-DELIVERY-METHOD-RESULT-ALREADY-EXISTS';
}
class UpdateDeliveryMethodResult {
	const OK = 'UPDATE-DELIVERY-METHOD-RESULT-OK';
	const FAILED = 'UPDATE-DELIVERY-METHOD-RESULT-FAILED';
	const DOES_NOT_EXIST = 'UPDATE-DELIVERY-METHOD-RESULT-DOES-NOT-EXIST';
}
class CreateImageResult {
	const CREATE_IMAGE_OK = 'CREATE-IMAGE-OK';
	const CREATE_IMAGE_TOO_LARGE = 'CREATE-IMAGE-TOO-LARGE';
	const CREATE_IMAGE_STORAGE_ERROR = 'CREATE-IMAGE-STORAGE-ERROR';
	const CREATE_IMAGE_NOT_SUPPORTED = 'CREATE-IMAGE-NOT-SUPPORTED';
}
class PrintLayoutType {
	const ALL = 'ALL';
	const RECEIPT = 'RECEIPT';
	const GRAPHICS = 'GRAPHICS';
}
class PrintLayoutKind {
	const ALL = 'ALL';
	const ARTICLE = 'ARTICLE';
	const RELATION = 'RELATION';
	const EMPLOYEE = 'EMPLOYEE';
	const REGISTER_RECEIPT = 'REGISTER-RECEIPT';
	const INVOICE = 'INVOICE';
	const TABLE_ORDER_RECEIPT = 'TABLE-ORDER-RECEIPT';
	const INTERMEDIATE_ORDER_RECEIPT = 'INTERMEDIATE-ORDER-RECEIPT';
	const SALE_ORDER = 'SALE-ORDER';
	const SALE_PACKING_RECEIPT = 'SALE-PACKING-RECEIPT';
	const TICKET = 'TICKET';
	const ORDER_TICKET = 'ORDER-TICKET';
	const TICKETCOUNTER_TICKET = 'TICKETCOUNTER-TICKET';
	const DEPOSIT_SLIP = 'DEPOSIT-SLIP';
	const PURCHASE_DELIVERY = 'PURCHASE-DELIVERY';
	const PURCHASE_ORDER = 'PURCHASE-ORDER';
	const PARTIAL_PAYMENT = 'PARTIAL-PAYMENT';
	const QUOTATION = 'QUOTATION';
	const MENU_PLANNING = 'MENU-PLANNING';
	const ORDER_SLIP = 'ORDER-SLIP';
}
class GetPrintLayoutsResponseResult {
	const OK = 'OK';
	const NO_PRINT_LAYOUTS_FOUND = 'NO-PRINT-LAYOUTS-FOUND';
}
class RenderedPrintLayoutType {
	const PDF = 'PDF';
	const PNG = 'PNG';
	const JPEG = 'JPEG';
}
class GetRenderedPrintLayoutResponseResult {
	const OK = 'OK';
	const PRINT_LAYOUT_NOT_FOUND = 'PRINT-LAYOUT-NOT-FOUND';
	const INVALID_PRINT_INFO = 'INVALID-PRINT-INFO';
	const RENDERING_FAILED = 'RENDERING-FAILED';
	const COULDNT_OPEN_FILE = 'COULDNT-OPEN-FILE';
	const THIS_LAYOUT_KIND_DOESNT_EXPECT_ANY_PRINT_INFO = 'THIS-LAYOUT-KIND-DOESNT-EXPECT-ANY-PRINT-INFO';
}
class VoucherActivationMoment {
	const ISSUE_DATE = 'ISSUE-DATE';
	const START_OF_DAY = 'START-OF-DAY';
	const START_OF_WEEK = 'START-OF-WEEK';
	const START_OF_MONTH = 'START-OF-MONTH';
	const START_OF_YEAR = 'START-OF-YEAR';
	const CHOICE = 'CHOICE';
}
class VoucherActivationDurationPeriod {
	const DAY = 'DAY';
	const WEEK = 'WEEK';
	const MONTH = 'MONTH';
	const YEAR = 'YEAR';
	const UNLIMITED = 'UNLIMITED';
}
class VoucherUseRelation {
	const REQUIRED = 'REQUIRED';
	const IF_SELECTED = 'IF-SELECTED';
	const NO = 'NO';
}
class VoucherLineType {
	const ARTICLE = 'ARTICLE';
	const TURNOVER_GROUP = 'TURNOVER-GROUP';
}
class GiftcardResult {
	const RESULT_OK = 'RESULT-OK';
	const RESULT_GIFTCARD_UNKNOWN = 'RESULT-GIFTCARD-UNKNOWN';
	const RESULT_GIFTCARD_NOT_ACTIVE = 'RESULT-GIFTCARD-NOT-ACTIVE';
	const RESULT_GIFTCARD_EXPIRED = 'RESULT-GIFTCARD-EXPIRED';
	const RESULT_GIFTCARD_NOT_VALID_FOR_BRANCH = 'RESULT-GIFTCARD-NOT-VALID-FOR-BRANCH';
	const RESULT_GIFTCARD_UNSUFFICIENT_BALANCE = 'RESULT-GIFTCARD-UNSUFFICIENT-BALANCE';
	const RESULT_GIFTCARD_INVALID_DEVALUATE_AMOUNT = 'RESULT-GIFTCARD-INVALID-DEVALUATE-AMOUNT';
	const RESULT_GIFTCARD_CARDNUMMER_ALREADY_TAKEN = 'RESULT-GIFTCARD-CARDNUMMER-ALREADY-TAKEN';
	const RESULT_GIFTCARD_UNKNOWN_RELATION = 'RESULT-GIFTCARD-UNKNOWN-RELATION';
	const RESULT_GIFTCARD_INVALID_RELOAD_AMOUNT = 'RESULT-GIFTCARD-INVALID-RELOAD-AMOUNT';
	const RESULT_GIFTCARD_UNABLE_TO_RELOAD = 'RESULT-GIFTCARD-UNABLE-TO-RELOAD';
	const RESULT_GIFTCARD_OFFLINE_NOT_ALLOWED = 'RESULT-GIFTCARD-OFFLINE-NOT-ALLOWED';
}
class GiftcardBookingType {
	const INITIAL_VALUE = 'INITIAL-VALUE';
	const CREATION = 'CREATION';
	const RELOAD = 'RELOAD';
	const DEVALUATE = 'DEVALUATE';
	const PAYMENT = 'PAYMENT';
	const REMIT = 'REMIT';
	const DEACTIVATE = 'DEACTIVATE';
	const START_BALANCE = 'START-BALANCE';
}
class SaveGiftcardsResult {
	const OK = 'SAVE-GIFTCARDS-RESULT-OK';
	const FAILED = 'SAVE-GIFTCARDS-RESULT-FAILED';
	const NOT_FOUND = 'SAVE-GIFTCARDS-RESULT-NOT-FOUND';
}
class RestituteGiftcardsResult {
	const OK = 'RESTITUTE-GIFTCARDS-RESULT-OK';
	const FAILED = 'RESTITUTE-GIFTCARDS-RESULT-FAILED';
	const NOT_FOUND = 'RESTITUTE-GIFTCARDS-RESULT-NOT-FOUND';
	const NO_BALANCE = 'RESTITUTE-GIFTCARDS-RESULT-NO-BALANCE';
}
class LinkGiftcardsToRelationResult {
	const LINK_GIFTCARDS_TO_RELATION_SUCCESS = 'LINK-GIFTCARDS-TO-RELATION-SUCCESS';
	const LINK_GIFTCARDS_TO_RELATION_INVALID_RELATION = 'LINK-GIFTCARDS-TO-RELATION-INVALID-RELATION';
	const LINK_GIFTCARDS_TO_RELATION_INVALID_ISSUANCE_ID = 'LINK-GIFTCARDS-TO-RELATION-INVALID-ISSUANCE-ID';
	const LINK_GIFTCARDS_TO_RELATION_ALREADY_LINKED_TO_RELATION = 'LINK-GIFTCARDS-TO-RELATION-ALREADY-LINKED-TO-RELATION';
	const LINK_GIFTCARDS_TO_RELATION_CANT_LINK_HAS_HISTORY_OTHER_RELATION = 'LINK-GIFTCARDS-TO-RELATION-CANT-LINK-HAS-HISTORY-OTHER-RELATION';
}
class AverageSpendingSource {
	const RECEIPT = 'AVERAGE-SPENDING-SOURCE-RECEIPT';
	const TABLE = 'AVERAGE-SPENDING-SOURCE-TABLE';
}
class ReportTurnoverSource {
	const INVOICE = 'REPORT-TURNOVER-SOURCE-INVOICE';
	const RECEIPT = 'REPORT-TURNOVER-SOURCE-RECEIPT';
	const CASH_INFLOW = 'REPORT-TURNOVER-SOURCE-CASH-INFLOW';
	const CASH_OUTFLOW = 'REPORT-TURNOVER-SOURCE-CASH-OUTFLOW';
}
class PaymentSourceType {
	const RECEIPT = 'PAYMENT-SOURCE-TYPE-RECEIPT';
	const CREDIT_RECEIPT = 'PAYMENT-SOURCE-TYPE-CREDIT-RECEIPT';
	const CASH_INFLOW = 'PAYMENT-SOURCE-TYPE-CASH-INFLOW';
	const CASH_OUTFLOW = 'PAYMENT-SOURCE-TYPE-CASH-OUTFLOW';
	const PAYMENT_METHOD_TRANSFER = 'PAYMENT-SOURCE-TYPE-PAYMENT-METHOD-TRANSFER';
	const INVOICE = 'PAYMENT-SOURCE-TYPE-INVOICE';
	const DIRECT_INVOICE = 'PAYMENT-SOURCE-TYPE-DIRECT-INVOICE';
	const CREDIT_INVOICE = 'PAYMENT-SOURCE-TYPE-CREDIT-INVOICE';
	const REPEATING_INVOICE = 'PAYMENT-SOURCE-TYPE-REPEATING-INVOICE';
	const EXTERNAL_INVOICE = 'PAYMENT-SOURCE-TYPE-EXTERNAL-INVOICE';
	const SALES_ORDER = 'PAYMENT-SOURCE-TYPE-SALES-ORDER';
	const REPEAT_SALES_ORDER = 'PAYMENT-SOURCE-TYPE-REPEAT-SALES-ORDER';
	const EXTERNAL_SALES_ORDER = 'PAYMENT-SOURCE-TYPE-EXTERNAL-SALES-ORDER';
	const TABLE_ORDER = 'PAYMENT-SOURCE-TYPE-TABLE-ORDER';
	const CAFETERIA_ORDER = 'PAYMENT-SOURCE-TYPE-CAFETERIA-ORDER';
	const UNKNOWN = 'PAYMENT-SOURCE-TYPE-UNKNOWN';
}
class ReportPrintableFinancialTotalsOption {
	const ACCOUNT_NUMBERS = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-ACCOUNT-NUMBERS';
	const RETURNS = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-RETURNS';
	const RETURNS_CONDENSED = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-RETURNS-CONDENSED';
	const POINTS = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-POINTS';
	const DRAWER_OPENINGS = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-DRAWER-OPENINGS';
	const DRAWER_OPENINGS_CONDENSED = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-DRAWER-OPENINGS-CONDENSED';
	const CASH_INFLOW_OUTFLOW = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-CASH-INFLOW-OUTFLOW';
	const DISCOUNTS = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-DISCOUNTS';
	const OPEN_TABLES = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-OPEN-TABLES';
	const CANCELLED_ORDERS = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-CANCELLED-ORDERS';
	const CANCELLED_ORDERS_CONDENSED = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-CANCELLED-ORDERS-CONDENSED';
	const MISTAKES = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-MISTAKES';
	const MISTAKES_CONDENSED = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-MISTAKES-CONDENSED';
	const POS_CLOSED = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-POS-CLOSED';
	const POS_CLOSED_CONDENSED = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-POS-CLOSED-CONDENSED';
	const CASH_COUNTS_CONDENSED = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-CASH-COUNTS-CONDENSED';
	const CONDENSE_EFT = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-CONDENSE-EFT';
	const EFT_REFUNDS = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-EFT-REFUNDS';
	const EMPLOYEES = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-EMPLOYEES';
	const AVERAGE_SPENDING = 'REPORT-PRINTABLE-FINANCIAL-TOTALS-OPTION-AVERAGE-SPENDING';
}
class SalesRepeatTemplateType {
	const ORDER = 'SALES-REPEAT-TEMPLATE-TYPE-ORDER';
	const INVOICE = 'SALES-REPEAT-TEMPLATE-TYPE-INVOICE';
}
class SalesRepeatTemplateState {
	const STARTED = 'SALES-REPEAT-TEMPLATE-STATE-STARTED';
	const PAUSED = 'SALES-REPEAT-TEMPLATE-STATE-PAUSED';
	const ENDED = 'SALES-REPEAT-TEMPLATE-STATE-ENDED';
}
class RepeatInterval {
	const NONE = 'REPEAT-INTERVAL-NONE';
	const WEEKLY = 'REPEAT-INTERVAL-WEEKLY';
	const MONTHLY = 'REPEAT-INTERVAL-MONTHLY';
	const QUARTERLY = 'REPEAT-INTERVAL-QUARTERLY';
}
class WhichWeeks {
	const SPECIFIC = 'WHICH-WEEKS-SPECIFIC';
	const ODD = 'WHICH-WEEKS-ODD';
	const EVEN = 'WHICH-WEEKS-EVEN';
	const ALL = 'WHICH-WEEKS-ALL';
}
class SaveSalesRepeatTemplateResult {
	const OK = 'SAVE-SALES-REPEAT-TEMPLATE-RESULT-OK';
	const NOT_FOUND = 'SAVE-SALES-REPEAT-TEMPLATE-RESULT-NOT-FOUND';
	const HAS_CHANGED = 'SAVE-SALES-REPEAT-TEMPLATE-RESULT-HAS-CHANGED';
	const FAILED = 'SAVE-SALES-REPEAT-TEMPLATE-RESULT-FAILED';
}
class BpeBudgetCheckResult {
	const PERFORM_BPE_BUDGET_CHECKS_RESULT_OK = 'PERFORM-BPE-BUDGET-CHECKS-RESULT-OK';
	const PERFORM_BPE_BUDGET_CHECKS_RESULT_WARN = 'PERFORM-BPE-BUDGET-CHECKS-RESULT-WARN';
	const PERFORM_BPE_BUDGET_CHECKS_RESULT_BLOCK = 'PERFORM-BPE-BUDGET-CHECKS-RESULT-BLOCK';
}
class PerformBpeBudgetChecksResult {
	const CHECK_BUDGETS_RESULT_OK = 'CHECK-BUDGETS-RESULT-OK';
	const CHECK_BUDGETS_RESULT_FAILED = 'CHECK-BUDGETS-RESULT-FAILED';
}
class SaleType {
	const GROUP_DISCOUNT = 'GROUP-DISCOUNT';
	const SLIDING_SCALE = 'SLIDING-SCALE';
	const X_FOR_Y = 'X-FOR-Y';
	const MIX_MATCH = 'MIX-MATCH';
	const SET = 'SET';
	const INDIVIDUAL = 'INDIVIDUAL';
	const CASH_DISCOUNT = 'CASH-DISCOUNT';
	const ARRANGEMENT = 'ARRANGEMENT';
}
class DiscountPercentageType {
	const DISCOUNT_ON_CHEAPEST = 'DISCOUNT-ON-CHEAPEST';
	const DISCOUNT_ON_ALL = 'DISCOUNT-ON-ALL';
}
class CreateOrderResult {
	const OK = 'CREATE-ORDER-RESULT-OK';
	const EXT_ORDER_ID_ALREADY_EXISTS = 'CREATE-ORDER-RESULT-EXT-ORDER-ID-ALREADY-EXISTS';
	const FAILED = 'CREATE-ORDER-RESULT-FAILED';
}
class PayOrderResult {
	const OK = 'PAY-ORDER-RESULT-OK';
	const FAILED = 'PAY-ORDER-RESULT-FAILED';
	const ORDER_HAS_CHANGED = 'PAY-ORDER-RESULT-ORDER-HAS-CHANGED';
	const PAYMENT_INSUFFICIENT = 'PAY-ORDER-RESULT-PAYMENT-INSUFFICIENT';
	const ORDER_ALREADY_INVOICED = 'PAY-ORDER-RESULT-ORDER-ALREADY-INVOICED';
}
class ProposalType {
	const PROPOSAL = 'PROPOSAL-TYPE-PROPOSAL';
}
class ProposalState {
	const OUTSTANDING = 'PROPOSAL-STATE-OUTSTANDING';
	const ORDER = 'PROPOSAL-STATE-ORDER';
	const INVOICE = 'PROPOSAL-STATE-INVOICE';
	const CANCELLED = 'PROPOSAL-STATE-CANCELLED';
}
class GetProposalResult {
	const OK = 'GET-PROPOSAL-RESULT-OK';
	const NOT_FOUND = 'GET-PROPOSAL-RESULT-NOT-FOUND';
}
class SaveProposalResult {
	const OK = 'SAVE-PROPOSAL-RESULT-OK';
	const NOT_FOUND = 'SAVE-PROPOSAL-RESULT-NOT-FOUND';
	const PROPOSAL_HAS_CHANGED = 'SAVE-PROPOSAL-RESULT-PROPOSAL-HAS-CHANGED';
	const FAILED = 'SAVE-PROPOSAL-RESULT-FAILED';
	const EXT_PROPOSAL_ID_ALREADY_EXISTS = 'SAVE-PROPOSAL-RESULT-EXT-PROPOSAL-ID-ALREADY-EXISTS';
}
class CancelProposalResult {
	const OK = 'CANCEL-PROPOSAL-RESULT-OK';
	const FAILED = 'CANCEL-PROPOSAL-RESULT-FAILED';
	const NOT_FOUND = 'CANCEL-PROPOSAL-RESULT-NOT-FOUND';
}
class CreateOrderFromProposalResult {
	const OK = 'CREATE-ORDER-FROM-PROPOSAL-RESULT-OK';
	const NOT_FOUND = 'CREATE-ORDER-FROM-PROPOSAL-RESULT-NOT-FOUND';
	const FAILED = 'CREATE-ORDER-FROM-PROPOSAL-RESULT-FAILED';
}
class CreateInvoiceFromProposalResult {
	const OK = 'CREATE-INVOICE-FROM-PROPOSAL-RESULT-OK';
	const NOT_FOUND = 'CREATE-INVOICE-FROM-PROPOSAL-RESULT-NOT-FOUND';
	const FAILED = 'CREATE-INVOICE-FROM-PROPOSAL-RESULT-FAILED';
}
class WebhookAuthenticationType {
	const TOKEN = 'WEBHOOK-AUTHENTICATION-TYPE-TOKEN';
	const CLOUD_CREDENTIALS = 'WEBHOOK-AUTHENTICATION-TYPE-CLOUD-CREDENTIALS';
}
class CodeType {
	const QRCODE = 'CODE-TYPE-QRCODE';
	const BARCODE = 'CODE-TYPE-BARCODE';
}
class WebhookFormFieldType {
	const TEXT = 'TEXT';
	const EMAIL = 'EMAIL';
	const PASSWORD = 'PASSWORD';
	const POSTALCODE = 'POSTALCODE';
	const NUMBER = 'NUMBER';
	const DATE = 'DATE';
	const TIME = 'TIME';
	const DATETIME = 'DATETIME';
	const SELECT = 'SELECT';
	const CHECKBOX = 'CHECKBOX';
	const LABEL = 'LABEL';
}
class ScanCodeType {
	const BARCODE = 'SCAN-CODE-TYPE-BARCODE';
	const RFID = 'SCAN-CODE-TYPE-RFID';
}
class WebhookErrorType {
	const REQUEST = 'WEBHOOK-ERROR-TYPE-REQUEST';
	const RESPONSE = 'WEBHOOK-ERROR-TYPE-RESPONSE';
}
class ExternalPaymentReceiptTextType {
	const CARDHOLDER = 'EXTERNAL-PAYMENT-RECEIPT-TEXT-TYPE-CARDHOLDER';
	const MERCHANT = 'EXTERNAL-PAYMENT-RECEIPT-TEXT-TYPE-MERCHANT';
}
class WebhookEvent {
	const SCAN_CODE = 'WEBHOOK-EVENT-SCAN-CODE';
	const ADD_SESSION_LINE = 'WEBHOOK-EVENT-ADD-SESSION-LINE';
	const UPDATE_SESSION_LINE = 'WEBHOOK-EVENT-UPDATE-SESSION-LINE';
	const REMOVE_SESSION_LINE = 'WEBHOOK-EVENT-REMOVE-SESSION-LINE';
	const SELECT_RELATION = 'WEBHOOK-EVENT-SELECT-RELATION';
	const CUSTOM_ACTION = 'WEBHOOK-EVENT-CUSTOM-ACTION';
	const START_PAYMENT = 'WEBHOOK-EVENT-START-PAYMENT';
	const CANCEL_PAYMENT = 'WEBHOOK-EVENT-CANCEL-PAYMENT';
}
